const completedMissionData = [
  [
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
  ],
  [
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
  ],
  [
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
    {
      type: '운동',
      title: '마라톤 같이 뛰어요!',
      fee: 1000,
      participant: 300,
      Dropout: 100,
    },
  ],
];

export default completedMissionData;
